spring:
  datasource:
    url: jdbc:h2:mem:testdb

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: true

    show-sql: true
  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  health:
    defaults:
      enabled: true

logging:
  level:
    ROOT: INFO
  file:
    name: "library.log"