spring:
  datasource:
    url: jdbc:h2:mem:testdb

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: true

    show-sql: true
  sql:
    init:
      schema-locations: schema.sql
      data-locations: data.sql
      mode: always


logging:
  level:
    ROOT: ERROR