# Бэк

apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-end-deployment
spec:
  selector:
    matchLabels:
      app: back-end-pod
  template:
    metadata:
      labels:
        app: back-end-pod
    spec:
      containers:
        - name: back-end
          image: localhost:5000/library-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: back-end
spec:
  type: NodePort
  selector:
    app: back-end-pod
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001
---

# Фронт

apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end-deployment
spec:
  selector:
    matchLabels:
      app: front-end-pod
  template:
    metadata:
      labels:
        app: front-end-pod
    spec:
      containers:
        - name: front-end
          image: localhost:5000/front-end:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: front-end
spec:
  type: NodePort
  selector:
    app: front-end-pod
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30002
---